"""Shared application constants."""

TODO_PRIORITY_LOW = "low"
TODO_PRIORITY_MEDIUM = "medium"
TODO_PRIORITY_HIGH = "high"

DEFAULT_TODO_PRIORITY = TODO_PRIORITY_LOW
VALID_TODO_PRIORITIES = (
    DEFAULT_TODO_PRIORITY,
    TODO_PRIORITY_MEDIUM,
    TODO_PRIORITY_HIGH,
)
